import React, { useEffect, useState } from 'react';
import { Calendar, HeartPulse } from 'lucide-react';
import { patientService } from '../services/api';

export default function PatientHistory({ patientId, refreshKey = 0 }) {
  const [history, setHistory] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  useEffect(() => { setLoading(true); patientService.getPatientById(patientId).then(({ data }) => setHistory(data.medical_history || [])).catch(() => setError('Unable to load medical history.')).finally(() => setLoading(false)); }, [patientId, refreshKey]);
  return <section className="med-card p-5"><div className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3"><h2 className="text-sm font-bold uppercase tracking-wider text-slate-800 flex items-center gap-2"><HeartPulse className="w-4 h-4 text-[#0e7c5b]" />Recorded Medical History</h2><span className="text-xs bg-emerald-50 text-emerald-800 border border-emerald-200 px-2.5 py-0.5 rounded-full font-semibold">{history.length} entries</span></div>{loading && <p className="py-8 text-xs text-slate-400">Loading clinician-reviewed history…</p>}{error && <p className="py-4 text-xs text-rose-700">{error}</p>}{!loading && !error && (history.length ? <div className="mt-4 space-y-3">{history.map((item) => <article key={item.id} className="rounded-xl border border-[#e2ece7] bg-[#fbfdfc] p-3.5"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-bold text-sm text-slate-800">{item.condition}</h3><span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded-full border bg-amber-50 text-amber-800 border-amber-200">{item.status}</span></div>{item.description && <p className="mt-2 text-xs text-slate-600 bg-white border border-slate-100 rounded-lg p-2">{item.description}</p>}</div><span className="shrink-0 flex items-center gap-1 text-[11px] text-slate-400"><Calendar className="w-3 h-3" />{item.diagnosis_date || new Date(item.created_at).toLocaleDateString()}</span></div></article>)}</div> : <p className="py-8 text-center text-xs text-slate-400">No clinician-reviewed medical history has been recorded.</p>)}<div className="mt-4 pt-3 border-t border-slate-100 flex justify-between text-[11px] text-slate-500"><span>Synchronized with medical_history records</span><span className="font-medium text-[#0e7c5b]">Doctor verified</span></div></section>;
}
