import React, { useState } from 'react';
import { BrainCircuit, AlertTriangle, BarChart3 } from 'lucide-react';
import api from '../services/api';

const defaults = { time_in_hospital: 3, num_lab_procedures: 40, num_procedures: 0, num_medications: 12, number_outpatient: 0, number_emergency: 0, number_inpatient: 0, number_diagnoses: 5 };
const labels = { time_in_hospital: 'Days in hospital', num_lab_procedures: 'Lab procedures', num_procedures: 'Procedures', num_medications: 'Medications', number_outpatient: 'Outpatient visits', number_emergency: 'Emergency visits', number_inpatient: 'Inpatient visits', number_diagnoses: 'Diagnoses' };

export default function XaiAnalysis({ patientId }) {
  const [form, setForm] = useState(defaults), [result, setResult] = useState(null), [global, setGlobal] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const predict = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { setResult((await api.post(`/xai/patients/${patientId}/predict`, form)).data); } catch (e) { setError(e.response?.data?.detail || 'Prediction is unavailable.'); } finally { setLoading(false); } };
  const loadGlobal = async () => { setLoading(true); setError(''); try { setGlobal((await api.get('/xai/global')).data); } catch (e) { setError(e.response?.data?.detail || 'Global analysis is unavailable.'); } finally { setLoading(false); } };
  return <section className="med-card p-5 md:col-span-2"><div className="flex justify-between gap-3 border-b border-slate-100 pb-3"><div className="flex gap-2"><BrainCircuit className="w-5 h-5 text-[#0e7c5b]" /><div><h2 className="text-sm font-bold text-slate-800">Readmission prediction & explainability</h2><p className="text-[11px] text-slate-500">Week 10 · XGBoost with local SHAP explanation</p></div></div><span className="text-[10px] bg-emerald-50 text-emerald-800 border border-emerald-200 px-2 py-0.5 rounded h-fit">Doctor review</span></div>
    <form onSubmit={predict} className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">{Object.entries(form).map(([key, value]) => <label key={key} className="text-[11px] text-slate-600">{labels[key]}<input type="number" min="0" value={value} onChange={(e) => setForm({ ...form, [key]: Number(e.target.value) })} className="input-med text-xs mt-1" /></label>)}<div className="col-span-2 md:col-span-4 flex gap-2"><button disabled={loading} className="btn-med-primary text-xs">{loading ? 'Analysing…' : 'Run prediction & SHAP'}</button><button type="button" disabled={loading} onClick={loadGlobal} className="btn-med-secondary text-xs flex gap-1 items-center"><BarChart3 className="w-3.5 h-3.5" />Load global XAI</button></div></form>
    {error && <p className="mt-3 text-xs text-rose-700">{error}</p>}
    {result && <div className="mt-5 space-y-4"><div className="rounded-xl bg-emerald-50 border border-emerald-100 p-4"><p className="text-xs font-semibold text-emerald-900">Estimated model score</p><p className="text-3xl font-bold text-[#0f4c3a]">{(result.probability * 100).toFixed(1)}%</p><p className="text-[11px] text-slate-600 mt-1">{result.model_label}; not a diagnosis or a reliable clinical probability without validation.</p></div>{result.ood_warning && <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900 flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0" />{result.ood_warning}</p>}{result.illustrative_counterfactual && <p className="rounded-lg border border-sky-200 bg-sky-50 p-3 text-xs text-sky-900">{result.illustrative_counterfactual}</p>}<Factor title="Features increasing the model score" items={result.increasing_factors} positive /><Factor title="Features decreasing the model score" items={result.decreasing_factors} /><div className="text-[11px] text-slate-500">{result.data_quality.map((x) => <p key={x}>• {x}</p>)}<p className="mt-2 text-amber-800">{result.disclaimer}</p></div></div>}
    {global && <div className="mt-5 border-t border-slate-100 pt-4"><h3 className="text-xs font-bold text-slate-700">Global SHAP importance</h3><Factor items={global.global_shap.map((x) => ({ feature: x.feature, contribution: x.mean_abs_shap }))} /><h3 className="mt-4 text-xs font-bold text-slate-700">Permutation importance (ROC-AUC decrease)</h3><Factor items={global.permutation_importance.map((x) => ({ feature: x.feature, contribution: x.importance }))} /><div className="mt-4 text-[11px] text-slate-500"><p>{global.calibration_note}</p>{Object.entries(global.pdp_ice).map(([name, plot]) => <Plot key={name} name={name} plot={plot} />)}</div></div>}</section>;
}
function Factor({ title, items = [], positive }) { const max = Math.max(...items.map((x) => Math.abs(x.contribution)), .001); return <div className="mt-3"><p className="text-[11px] font-semibold text-slate-600">{title}</p>{items.length ? items.map((x) => <div key={x.feature} className="mt-2 text-[11px]"><div className="flex justify-between gap-2"><span>{x.feature}</span><span className={positive ? 'text-rose-700' : 'text-emerald-700'}>{x.contribution > 0 ? '+' : ''}{x.contribution}</span></div><div className="h-1.5 bg-slate-100 rounded"><div className={positive ? 'h-full bg-rose-400 rounded' : 'h-full bg-emerald-500 rounded'} style={{ width: `${Math.abs(x.contribution) / max * 100}%` }} /></div></div>) : <p className="text-[11px] text-slate-400 mt-1">No material factors found.</p>}</div>; }
function Plot({ name, plot }) { const lines = [plot.pdp, ...plot.ice]; const max = Math.max(...lines.flat()), min = Math.min(...lines.flat()); const points = (values) => values.map((v, i) => `${i / (values.length - 1) * 280 + 10},${90 - (v - min) / Math.max(max - min, .001) * 75}`).join(' '); return <div className="mt-4 rounded-lg border border-slate-100 p-3"><p className="font-semibold text-slate-700">{name}: partial dependence and ICE</p><svg viewBox="0 0 300 100" className="w-full max-w-md h-28 mt-2 bg-slate-50 rounded"><line x1="10" x2="290" y1="90" y2="90" stroke="#cbd5e1" />{plot.ice.map((line, i) => <polyline key={i} points={points(line)} fill="none" stroke="#94a3b8" strokeWidth="1" opacity=".45" />)}<polyline points={points(plot.pdp)} fill="none" stroke="#0e7c5b" strokeWidth="3" /><text x="10" y="99" fontSize="8">{plot.values[0]}</text><text x="250" y="99" fontSize="8">{plot.values.at(-1)}</text></svg><p>Green = average model response (PDP); gray = eight individual encounter responses (ICE).</p></div>; }
