import React, { useEffect, useState } from 'react';
import { Bot, FileText, Send, ShieldCheck } from 'lucide-react';
import api, { patientService } from '../services/api';
import ClinicalDisclaimer from '../components/ClinicalDisclaimer';

export default function ClinicalAssistant() {
  const [patients, setPatients] = useState([]), [patientId, setPatientId] = useState('');
  const [question, setQuestion] = useState('Summarize the relevant guideline evidence for diabetes screening.');
  const [result, setResult] = useState(null), [draft, setDraft] = useState(null), [loading, setLoading] = useState(false), [error, setError] = useState('');
  useEffect(() => { patientService.getPatients().then(({ data }) => setPatients(data)).catch(() => setError('Unable to load patients.')); }, []);
  const ask = async (event) => { event.preventDefault(); setLoading(true); setError(''); setDraft(null); try { setResult((await api.post('/assistant/ask', { question, patient_id: patientId ? Number(patientId) : null })).data); } catch (err) { setError(err.response?.data?.detail || 'The assistant is unavailable.'); } finally { setLoading(false); } };
  const createDraft = async () => { if (!patientId) return setError('Select a patient before creating a record draft.'); setLoading(true); setError(''); setResult(null); try { setDraft((await api.get(`/assistant/patients/${patientId}/draft`)).data); } catch (err) { setError(err.response?.data?.detail || 'Could not create the record draft.'); } finally { setLoading(false); } };
  return <div className="max-w-4xl space-y-6"><div><h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2"><Bot className="w-6 h-6 text-[#0e7c5b]" />AI Clinical Assistant</h1><p className="mt-1 text-sm text-slate-500">Controlled guideline evidence and clinician-reviewed record navigation.</p></div><ClinicalDisclaimer />
    <section className="med-card p-5"><form onSubmit={ask} className="space-y-4"><div><label className="block text-xs font-semibold text-slate-700 mb-1">Optional patient context</label><select value={patientId} onChange={(e) => setPatientId(e.target.value)} className="input-med text-sm"><option value="">Guideline evidence only</option>{patients.map((p) => <option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></div><div><label className="block text-xs font-semibold text-slate-700 mb-1">Question</label><textarea value={question} onChange={(e) => setQuestion(e.target.value)} required minLength="3" rows="3" className="input-med text-sm" /></div><div className="flex flex-wrap gap-2"><button disabled={loading} className="btn-med-primary text-xs flex items-center gap-1.5"><Send className="w-3.5 h-3.5" />{loading ? 'Working…' : 'Ask from evidence'}</button><button type="button" onClick={createDraft} disabled={loading} className="btn-med-secondary text-xs flex items-center gap-1.5"><FileText className="w-3.5 h-3.5" />Create record draft</button></div></form>{error && <p className="mt-3 text-xs text-rose-700">{error}</p>}</section>
    {result && <section className="med-card p-5 space-y-4"><div><h2 className="font-bold text-slate-800">{result.status === 'answered' ? 'Evidence-grounded answer' : 'Retrieved evidence summary'}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-slate-700">{result.answer || result.message}</p></div>{result.patient_context && <div className="rounded-lg border border-sky-100 bg-sky-50/50 p-3 text-xs text-slate-700"><p className="font-semibold">Patient record navigation: {result.patient_context.patient_name}</p><p className="mt-1">Documented history: {result.patient_context.history.join(', ') || 'None recorded.'}</p><div className="mt-2">{result.patient_context.report_matches.length ? result.patient_context.report_matches.map((match, i) => <p key={i} className="mt-1">• {match}</p>) : 'No matching extracted-report passages found.'}</div></div>}<Evidence items={result.evidence} /></section>}
    {draft && <section className="med-card p-5"><h2 className="font-bold text-slate-800">Draft for doctor review</h2><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-relaxed text-slate-700">{draft.draft}</pre><p className="mt-3 flex gap-1.5 text-xs text-amber-800"><ShieldCheck className="w-4 h-4 shrink-0" />{draft.disclaimer}</p></section>}</div>;
}
function Evidence({ items = [] }) { return <div className="border-t border-slate-100 pt-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Retrieved sources</p>{items.map((item, i) => <article key={i} className="mt-3 rounded-lg border border-slate-100 p-3 text-xs"><p className="font-semibold text-slate-800">[{i + 1}] {item.source} <span className="font-normal text-slate-400">({item.score})</span></p><p className="mt-1 text-[#0e7c5b]">{item.section}</p><p className="mt-2 leading-relaxed text-slate-600">{item.text}</p></article>)}</div>; }
