import React, { useState } from 'react';
import { AlertTriangle, TrendingUp } from 'lucide-react';
import api from '../services/api';
import ClinicalDisclaimer from '../components/ClinicalDisclaimer';
import PatientPicker from '../components/PatientPicker';

const defaults = { time_in_hospital: 3, num_lab_procedures: 40, num_procedures: 0, num_medications: 12, number_outpatient: 0, number_emergency: 0, number_inpatient: 0, number_diagnoses: 5 };
const labels = { time_in_hospital: 'Days in hospital', num_lab_procedures: 'Lab procedures', num_procedures: 'Procedures', num_medications: 'Medications', number_outpatient: 'Outpatient visits', number_emergency: 'Emergency visits', number_inpatient: 'Inpatient visits', number_diagnoses: 'Diagnoses' };

export default function Readmission() {
  const [patientId, setPatientId] = useState(null), [form, setForm] = useState(defaults), [result, setResult] = useState(null), [loading, setLoading] = useState(false), [error, setError] = useState('');
  const predict = async (e) => { e.preventDefault(); setLoading(true); setError(''); try { setResult((await api.post(`/xai/patients/${patientId}/predict`, form)).data); } catch (err) { setError(err.response?.data?.detail || 'Prediction is unavailable.'); } finally { setLoading(false); } };
  return <div className="max-w-6xl space-y-6"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-800"><TrendingUp className="w-6 h-6 text-[#0e7c5b]" />XGBoost Readmission Prediction</h1><p className="mt-1 text-sm text-slate-500">Estimate the model’s 30-day readmission score for a selected patient encounter.</p></div><ClinicalDisclaimer /><PatientPicker onSelect={setPatientId} />{patientId && <section className="med-card p-5"><div className="flex justify-between border-b border-slate-100 pb-3"><div><h2 className="text-sm font-bold text-slate-800">Readmission prediction</h2><p className="text-[11px] text-slate-500">XGBoost model score only — use the separate SHAP menu for explanations.</p></div><span className="text-[10px] bg-emerald-50 text-emerald-800 border border-emerald-200 px-2 py-0.5 rounded">Doctor review</span></div><form onSubmit={predict} className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">{Object.entries(form).map(([key, value]) => <label key={key} className="text-[11px] text-slate-600">{labels[key]}<input type="number" min="0" value={value} onChange={(e) => setForm({ ...form, [key]: Number(e.target.value) })} className="input-med text-xs mt-1" /></label>)}<div className="col-span-2 md:col-span-4"><button disabled={loading} className="btn-med-primary text-xs">{loading ? 'Analysing…' : 'Run prediction'}</button></div></form>{error && <p className="mt-3 text-xs text-rose-700">{error}</p>}{result && <div className="mt-5"><div className="rounded-xl bg-emerald-50 border border-emerald-100 p-4"><p className="text-xs font-semibold text-emerald-900">Estimated model score</p><p className="text-3xl font-bold text-[#0f4c3a]">{(result.probability * 100).toFixed(1)}%</p><p className="text-[11px] text-slate-600 mt-1">{result.model_label}; not a diagnosis or reliable clinical probability without validation.</p></div>{result.ood_warning && <p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900 flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0" />{result.ood_warning}</p>}<p className="mt-3 text-[11px] text-amber-800">{result.disclaimer}</p></div>}</section>}</div>;
}
